import { DASHBOARDS_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import { ADMIN, USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

export const navigationConfig: NavigationTree[] = [
    {
        key: '',
        path: '',
        title: '',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        meta: {
            horizontalMenu: {
                layout: 'default',
            },
        },
        subMenu: [
            {
                key: 'dashboard',
                path: `/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.dashboard.dashboard',
                icon: 'dashboardDashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'employees',
                path: `/employees`,
                title: 'employees',
                translateKey: 'nav.dashboard.employees',
                icon: 'dashboardEmployees',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'attendance',
                path: `/attendance`,
                title: 'Attendance',
                translateKey: 'nav.dashboard.attendance',
                icon: 'dashboardAttendance',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'schedule',
                path: `/schedule`,
                title: 'Schedule',
                translateKey: 'nav.dashboard.schedule',
                icon: 'dashboardSchedule',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'leave',
                path: `/leave-list`,
                title: 'Leave',
                translateKey: 'nav.dashboard.leave',
                icon: 'dashboardLeave',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'reports',
                path: `/reports`,
                title: 'Reports',
                translateKey: 'nav.dashboard.reports',
                icon: 'dashboardReports',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'users',
                path: `/users`,
                title: 'Users',
                translateKey: 'nav.dashboard.users',
                icon: 'dashboardUsers',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'setting',
                path: `/setting`,
                title: 'Setting',
                translateKey: 'nav.dashboard.setting',
                icon: 'dashboardSetting',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
        ],
    },
]

export const personalNavigationConfig: NavigationTree[] = [
    {
        key: '',
        path: '',
        title: '',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        meta: {
            horizontalMenu: {
                layout: 'default',
            },
        },
        subMenu: [
            {
                key: 'personalDashboard',
                path: `/personal/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.dashboard.dashboard',
                icon: 'dashboardDashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'personalAttendance',
                path: `/personal/attendance`,
                title: 'My Attendance',
                translateKey: 'nav.dashboard.attendance',
                icon: 'dashboardAttendance',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'personalSchedule',
                path: `/personal/schedule`,
                title: 'My Schedule',
                translateKey: 'nav.dashboard.schedule',
                icon: 'dashboardSchedule',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
        ],
    },
]
